version: '3'

services:
  db:
    image: postgres:11.2
  api:
    build: ./api
    entrypoint: /code/entrypoint.sh
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
